"use client";

import { useState } from "react";
import type { CashCategory, CashCertainty, CashFlowEntry, CashFlowPlan, CashFlowView } from "../../domain/cash-flow";
import { calculateCashFlow, entryMatchesView, markCashEntryReceived } from "../../domain/cash-flow";
import { resaleHubProvider } from "../../integrations/resale-hub";

const views:CashFlowView[]=["September","October","Through Move","Move / Move-In Costs"];
const certainties:CashCertainty[]=["Available","Confirmed","Expected","Pending","Estimate","Unknown"];
const categories:CashCategory[]=["Bills","Move In","Physical Move","Income","Unemployment","Resale","Other"];
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
const freshness=(value:string)=>value?`Updated ${new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(value))}`:"Update needed";

export function CashFlowTool({plan,onChange,back}:{plan:CashFlowPlan;onChange:(plan:CashFlowPlan)=>void;back:()=>void}){
  const [view,setView]=useState<CashFlowView>("Through Move");
  const [draft,setDraft]=useState<CashFlowEntry|null>(null);
  const totals=calculateCashFlow(plan,view);
  const entries=plan.entries.filter(entry=>!entry.receivedAt&&entryMatchesView(entry,view));
  const connection=resaleHubProvider.getConnectionState();
  const addEntry=(direction:"in"|"out")=>setDraft({id:crypto.randomUUID(),label:"",direction,category:direction==="in"?"Income":"Bills",certainty:direction==="in"?"Expected":"Unknown",recurring:"none",includeInProjection:false,source:"manual"});
  return <div className="page cash-flow-page"><button className="back-link" onClick={back}>← Home</button><header className="cash-flow-header"><div><p className="eyebrow">Cash Flow for the Move</p><h1>What will actually be left when I arrive?</h1><p>Current cash, likely money in, required money out, and costs that still need real numbers.</p></div><label><span>View</span><select value={view} onChange={event=>setView(event.target.value as CashFlowView)}>{views.map(value=><option key={value}>{value}</option>)}</select></label></header>
    <section className="cash-position"><div><span>Cash available now</span><b>{money(totals.availableNow)}</b><small>Accounts + available resale</small></div><div><span>Expected before move</span><b>{money(totals.confirmedIncoming+totals.expectedIncoming)}</b><small>Confirmed + included expected</small></div><div><span>Bills + obligations</span><b>−{money(totals.billsAndObligations)}</b><small>Known and included estimates</small></div><div><span>Move + move-in</span><b>−{money(totals.moveAndMoveInCosts)}</b><small>{totals.unknownEntries.length?"Some costs still need estimates":"Known planning costs"}</small></div></section>
    <section className="net-positions"><article><span>Conservative position</span><b>{money(totals.conservativePosition)}</b><p>What can be counted on from available cash and confirmed entries.</p></article><article><span>Projected move position</span><b>{money(totals.projectedMovePosition)}</b><p>If the reasonable included plan happens, this is what may remain.</p></article></section>

    <section className="cash-section"><header><div><h2>Cash available now</h2><p>Only money that is usable today.</p></div><button onClick={()=>onChange({...plan,accounts:[...plan.accounts,{id:crypto.randomUUID(),label:"New account",balance:0,updatedAt:new Date().toISOString()}]})}>＋ Add account</button></header><div className="account-list">{plan.accounts.map(account=><label key={account.id}><div><input aria-label="Account name" value={account.label} onChange={event=>onChange({...plan,accounts:plan.accounts.map(candidate=>candidate.id===account.id?{...candidate,label:event.target.value,updatedAt:new Date().toISOString()}:candidate)})}/><small>{freshness(account.updatedAt)}</small></div><span>$</span><input aria-label={`${account.label} balance`} type="number" value={account.balance} onChange={event=>onChange({...plan,accounts:plan.accounts.map(candidate=>candidate.id===account.id?{...candidate,balance:Number(event.target.value)||0,updatedAt:new Date().toISOString()}:candidate)})}/><button aria-label={`Remove ${account.label}`} onClick={()=>onChange({...plan,accounts:plan.accounts.filter(candidate=>candidate.id!==account.id)})}>×</button></label>)}</div></section>

    <section className="cash-section"><header><div><h2>Expected money in</h2><p>Kept separate from cash you can spend today.</p></div><button onClick={()=>addEntry("in")}>＋ Add incoming</button></header><div className="cash-entry-list">{entries.filter(entry=>entry.direction==="in").map(entry=><CashEntryRow key={entry.id} entry={entry} edit={()=>setDraft(entry)} received={()=>onChange(markCashEntryReceived(plan,entry.id))}/>)}{!entries.some(entry=>entry.direction==="in")&&<p className="calm-empty">No expected money is included in this view.</p>}</div></section>

    <section className="cash-section"><header><div><h2>Money going out</h2><p>Bills, obligations, move-in, and physical move costs.</p></div><button onClick={()=>addEntry("out")}>＋ Add outgoing</button></header><div className="cash-entry-list">{entries.filter(entry=>entry.direction==="out").map(entry=><CashEntryRow key={entry.id} entry={entry} edit={()=>setDraft(entry)}/>)}{!entries.some(entry=>entry.direction==="out")&&<p className="calm-empty">No outgoing money is captured in this view.</p>}</div></section>

    <section className="cash-section resale-section"><header><div><h2>Resale balances</h2><p>Available balances count now. Pending balances count only when you include them.</p></div></header><div className="resale-list">{plan.resaleBalances.map(balance=><article key={balance.platform}><div><b>{balance.platform}</b><small>{freshness(balance.updatedAt)} · manual</small></div><label><span>Available</span><input type="number" value={balance.available} onChange={event=>onChange({...plan,resaleBalances:plan.resaleBalances.map(candidate=>candidate.platform===balance.platform?{...candidate,available:Number(event.target.value)||0,updatedAt:new Date().toISOString()}:candidate)})}/></label><label><span>Pending</span><input type="number" value={balance.pending} onChange={event=>onChange({...plan,resaleBalances:plan.resaleBalances.map(candidate=>candidate.platform===balance.platform?{...candidate,pending:Number(event.target.value)||0,updatedAt:new Date().toISOString()}:candidate)})}/></label><label className="include-pending"><input type="checkbox" checked={!!balance.includePendingInProjection} onChange={event=>onChange({...plan,resaleBalances:plan.resaleBalances.map(candidate=>candidate.platform===balance.platform?{...candidate,includePendingInProjection:event.target.checked}:candidate)})}/><span>Include pending</span></label></article>)}</div><aside className="integration-note"><span>Resale Hub</span><div><b>{connection.label}</b><p>Automatic balance sync is waiting on the Resale Hub balance feature. Manual balances work until then.</p></div><i>Sync coming after the balance endpoint is added</i></aside></section>

    {totals.unknownEntries.length>0&&<section className="cash-section unresolved"><header><div><h2>Still need numbers for</h2><p>Unknown does not mean zero.</p></div></header><div>{totals.unknownEntries.map(entry=><button key={entry.id} onClick={()=>setDraft({...entry,certainty:"Estimate",includeInProjection:true})}><b>{entry.label}</b><small>{entry.notes||"Add a planning estimate when ready."}</small><span>Add estimate →</span></button>)}</div></section>}
    <section className="cash-section change-drivers"><header><div><h2>What could change this</h2><p>The parts of the projection that are not final yet.</p></div></header><ul>{plan.entries.filter(entry=>["Pending","Expected","Estimate","Unknown"].includes(entry.certainty)&&!entry.receivedAt).slice(0,6).map(entry=><li key={entry.id}><b>{entry.label}</b><span>{entry.certainty}{entry.dueDate?` · ${entry.dueDate}`:""}</span></li>)}</ul></section>
    {draft&&<CashFlowEntryEditor entry={draft} close={()=>setDraft(null)} save={entry=>{onChange({...plan,entries:plan.entries.some(candidate=>candidate.id===entry.id)?plan.entries.map(candidate=>candidate.id===entry.id?entry:candidate):[...plan.entries,entry]});setDraft(null)}} remove={()=>{onChange({...plan,entries:plan.entries.filter(entry=>entry.id!==draft.id)});setDraft(null)}}/>}
  </div>;
}

function CashEntryRow({entry,edit,received}:{entry:CashFlowEntry;edit:()=>void;received?:()=>void}){
  return <article><button onClick={edit}><div><b>{entry.label}</b><small>{entry.category} · {entry.certainty}{entry.dueDate?` · due ${entry.dueDate}`:""}</small></div><strong>{entry.amount===undefined?"Amount still needed":money(entry.amount)}</strong></button>{received&&["Confirmed","Expected","Pending"].includes(entry.certainty)&&<button className="received" onClick={received}>Mark received</button>}</article>;
}

function CashFlowEntryEditor({entry,close,save,remove}:{entry:CashFlowEntry;close:()=>void;save:(entry:CashFlowEntry)=>void;remove:()=>void}){
  const [draft,setDraft]=useState(entry);
  return <div className="overlay" onMouseDown={event=>event.currentTarget===event.target&&close()}><form className="modal cash-entry-editor" onSubmit={event=>{event.preventDefault();save(draft)}}><header className="modal-head"><div><small>CASH FLOW</small><h2>{entry.label?"Edit entry":"Add entry"}</h2></div><button type="button" onClick={close}>×</button></header><label className="field"><span>Label</span><input autoFocus required value={draft.label} onChange={event=>setDraft({...draft,label:event.target.value})}/></label><div className="form-grid three"><label className="field"><span>Amount</span><input type="number" min="0" value={draft.amount??""} placeholder="Unknown is okay" onChange={event=>setDraft({...draft,amount:event.target.value===""?undefined:Number(event.target.value)})}/></label><label className="field"><span>Certainty</span><select value={draft.certainty} onChange={event=>setDraft({...draft,certainty:event.target.value as CashCertainty})}>{certainties.map(value=><option key={value}>{value}</option>)}</select></label><label className="field"><span>Category</span><select value={draft.category} onChange={event=>setDraft({...draft,category:event.target.value as CashCategory})}>{categories.map(value=><option key={value}>{value}</option>)}</select></label></div><div className="form-grid"><label className="field"><span>Due date</span><input type="date" value={draft.dueDate||""} onChange={event=>setDraft({...draft,dueDate:event.target.value||undefined})}/></label><label className="field"><span>Repeats</span><select value={draft.recurring||"none"} onChange={event=>setDraft({...draft,recurring:event.target.value as "none"|"monthly"})}><option value="none">Does not repeat</option><option value="monthly">Monthly</option></select></label></div><label className="switch"><div><b>Include in projected position</b><small>Use this number in the reasonable-plan projection.</small></div><input type="checkbox" checked={draft.includeInProjection} onChange={event=>setDraft({...draft,includeInProjection:event.target.checked})}/></label><label className="field"><span>Notes</span><textarea value={draft.notes||""} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label><footer className="modal-actions"><button type="button" className="delete" onClick={remove}>Delete</button><span/><button type="button" className="button" onClick={close}>Cancel</button><button className="button primary" type="submit">Save</button></footer></form></div>;
}
