import type { MoveData, MoveItem } from "./types";

const today = new Date().toISOString().slice(0, 10);
const item = (partial: Partial<MoveItem> & Pick<MoveItem, "id" | "title" | "area" | "section">): MoveItem => ({
  description: "", status: "Not started", priority: "Relief", timing: "Prepare early",
  stage: "Prepare", stream: "Clear", relationship: "Parallel", knowledgeStatus: "Known",
  kind: "Action",
  createdAt: today, updatedAt: today, ...partial,
});

export const seedData: MoveData = {
  schemaVersion: 7,
  profile: {
    reason: "I am building a life with more privacy, creativity, nature, meaningful connection, and financial peace.",
    destination: "Denver (current plan; Chicago and Boston were considered)",
    targetMoveDate: "2026-10-24",
    backupDate: "2026-10-31",
    phase: "Foundation / Prepare",
    currentUnlock: "Turn the financial and rental unknowns into facts while the rest of the plan keeps moving.",
    protectedMonth: true,
  },
  sectionTargets: {
    "Money, Credit and Old Obligations":"2026-09-15","Car, Documents and Responsibilities":"2026-10-01","Family: What I Can Help With":"2026-10-01","Closure Before I Leave":"2026-10-15","Allowed to Wait":"2026-10-24",
    "Timeline":"2026-10-24","Move Money":"2026-10-15","Post-Move Income":"2026-09-30","Rental Readiness":"2026-09-20","Housing and Lease":"2026-10-10","Land Softly":"2026-10-24","Physical Move":"2026-10-24",
    "The Life I Want":"2026-10-24","People and Relationships":"2026-10-15","Spiritual Preparation":"2026-10-24","Community and Belonging":"2026-11-30","Flowering Period: First 30 Days":"2026-11-23"
  },
  calendarTargets: {ground:"2026-08-31",test:"2026-09-30",commit:"2026-10-24",land:"2026-11-23"},
  items: [
    item({id:"credit-plan",title:"Build the rental-focused credit plan",description:"Use the Randall workbook to separate active accounts, collections, and the few balances that could affect approval. The goal is credible progress—not perfect credit.",area:"Clear",section:"Money, Credit and Old Obligations",priority:"Housing",timing:"Now",stage:"Foundation",stream:"Money",relationship:"Parallel",knowledgeStatus:"Known",unlocks:["rental-ready"]}),
    item({id:"credit-utilization",parentId:"credit-plan",title:"Choose which high-utilization balances to lower first",description:"Current utilization is mostly in the 90s. Prioritize the change most likely to help rental readiness.",area:"Clear",section:"Money, Credit and Old Obligations",priority:"Money",timing:"Now",stage:"Foundation",stream:"Money",relationship:"Helpful sequence",knowledgeStatus:"Estimate"}),
    item({id:"credit-collections",parentId:"credit-plan",title:"Verify the rental impact of the major collections",description:"Focus on Apple/Goldman, Citi, Capital One/Walmart, Xfinity, First Energy, Progressive, and GEICO—without assuming every balance must be cleared.",area:"Clear",section:"Money, Credit and Old Obligations",priority:"Housing",timing:"Now",stage:"Foundation",stream:"Money",relationship:"Helpful sequence",knowledgeStatus:"Need information"}),
    item({id:"credit-explanation",parentId:"credit-plan",title:"Draft a short credit explanation if target properties request one",description:"Keep it factual: collections, late payments, current stability, and documented plans.",area:"Clear",section:"Money, Credit and Old Obligations",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Housing",relationship:"Waiting on event",knowledgeStatus:"Waiting on event"}),
    item({id:"md-emissions",title:"Resolve Maryland emissions requirement",description:"Confirm the amount and deadline so registration or fees do not become an avoidable problem.",area:"Clear",section:"Money, Credit and Old Obligations",priority:"Deadline",timing:"Now",stage:"Foundation",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Need information"}),

    item({id:"car-ready",title:"Keep the car safe, legal, and ready for the drive",description:"The car is safe now. Only reliability and legal tasks belong in the move-critical plan.",area:"Clear",section:"Car, Documents and Responsibilities",priority:"Safety",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Known"}),
    item({id:"oil-change",parentId:"car-ready",title:"Schedule the pre-move oil change",description:"The only known reliability maintenance currently needed.",area:"Clear",section:"Car, Documents and Responsibilities",priority:"Safety",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Helpful sequence",knowledgeStatus:"Known"}),
    item({id:"registration",parentId:"car-ready",title:"Plan for registration expiring in November",description:"Research destination timing once Denver is confirmed; do not wait until after expiration.",area:"Clear",section:"Car, Documents and Responsibilities",priority:"Deadline",timing:"Prepare early",stage:"Decide",stream:"Clear",relationship:"Decision gate",knowledgeStatus:"Need information"}),
    item({id:"insurance",parentId:"car-ready",title:"Compare destination car-insurance requirements",description:"Current coverage is Progressive in Maryland; the final quote needs a destination address.",area:"Clear",section:"Car, Documents and Responsibilities",priority:"Money",timing:"Prepare early",stage:"Commit",stream:"Money",relationship:"Waiting on event",knowledgeStatus:"Need information"}),
    item({id:"attic",title:"Go through the attic",description:"Decide what travels, gets donated, or gets released before packing becomes urgent.",area:"Clear",section:"Car, Documents and Responsibilities",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Known"}),

    item({id:"family-plan",title:"Help Mom and Sister build a life plan they can own",description:"Offer structure around groceries, food preparation, cleaning, transportation, and finances. This is loving support—not a condition for your move.",area:"Clear",section:"Family: What I Can Help With",status:"In motion",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Decided"}),
    item({id:"family-transport",parentId:"family-plan",title:"Help Mom identify a license or transportation next step",description:"A finite practical action that could increase her independence.",area:"Clear",section:"Family: What I Can Help With",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Helpful sequence",knowledgeStatus:"Decided"}),
    item({id:"family-routine",parentId:"family-plan",title:"Write a simple food and home routine",description:"Show the system once and let it become theirs.",area:"Clear",section:"Family: What I Can Help With",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Decided"}),
    item({id:"grandma-letter",title:"Write the letter to Grandma",description:"Acknowledge that things did not land well, without making her response a requirement for closure.",area:"Clear",section:"Closure Before I Leave",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Decided"}),
    item({id:"goodbye-time",title:"Plan the people and places farewell list",description:"Friends, taking Mom out, Goodwill bins with your sister, the Inner Harbor, a game, The Eagle, and childhood places.",area:"Clear",section:"Closure Before I Leave",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Decided"}),
    item({id:"release-old",title:"Name what stays in Baltimore",description:"Obsessive mindsets, scarcity, insecurity, feeling behind or lesser, and hiding desire do not have to come with you.",area:"Clear",section:"Closure Before I Leave",status:"In motion",priority:"Relief",timing:"Now",stage:"Foundation",stream:"Become",relationship:"Informational",knowledgeStatus:"Known"}),
    item({kind:"Reference",referenceFor:["car-ready"],id:"cosmetic-car",title:"Fender, dents, scratches, and other cosmetic car work",description:"Emotionally meaningful, but the car is already safe. Revisit only if money and time genuinely allow.",area:"Clear",section:"Allowed to Wait",status:"Deferred",priority:"Someday",timing:"Allowed to wait",stage:"Land",stream:"Clear",relationship:"Deferred decision",knowledgeStatus:"Known"}),
    item({kind:"Reference",referenceFor:["family-plan"],id:"family-perfect",title:"Getting the family completely ready without you",description:"Their stability matters, but their perfect outcome is outside your control and cannot become the move gate.",area:"Clear",section:"Allowed to Wait",status:"Deferred",priority:"Someday",timing:"Allowed to wait",stage:"Land",stream:"Clear",relationship:"Informational",knowledgeStatus:"Decided"}),
    item({kind:"Reference",referenceFor:["apartments","arrival-kit"],id:"prebuy",title:"Buying everything early to avoid feeling lack",description:"Functional first. Most home purchases wait for measurements or lived experience.",area:"Clear",section:"Allowed to Wait",status:"Deferred",priority:"Someday",timing:"Allowed to wait",stage:"Land",stream:"Money",relationship:"Deferred decision",knowledgeStatus:"Decided"}),

    item({id:"income-options",title:"Keep three income routes credible",description:"Research and prepare now. The final route does not need to be chosen until timing and housing evidence make the choice useful.",area:"Build",section:"Post-Move Income",status:"In motion",priority:"Income",timing:"Now",stage:"Prepare",stream:"Income",relationship:"Parallel",knowledgeStatus:"Known"}),
    item({id:"remote-policy",parentId:"income-options",title:"Research out-of-state remote-work policy",description:"The company has remote roles and one known remote worker, but the exact policy still needs confirmation.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Now",stage:"Prepare",stream:"Income",relationship:"Parallel",knowledgeStatus:"Need information"}),
    item({id:"remote-case",parentId:"income-options",title:"Prepare a balanced remote-work case",description:"Protect the current $31.25/hour baseline and show performance, coverage, communication, and a workable transition.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Prepare early",stage:"Prepare",stream:"Income",relationship:"Helpful sequence",knowledgeStatus:"Need to think"}),
    item({id:"remote-talk",parentId:"income-options",title:"Begin the employer conversation around September",description:"Six months into the contract is the current working trigger.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Prepare early",dueDate:"2026-09-01",stage:"Decide",stream:"Income",relationship:"Decision gate",knowledgeStatus:"Estimate"}),
    item({id:"job-search",parentId:"income-options",title:"Begin applying for remote roles in September",description:"Target stable corporate work, 40 hours, and at least $75,000. This is a parallel option and useful leverage.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Prepare early",dueDate:"2026-09-01",stage:"Decide",stream:"Income",relationship:"Parallel",knowledgeStatus:"Decided"}),
    item({id:"income-decision",parentId:"income-options",title:"Choose the income route when the evidence is useful",description:"Use the late-September housing timeline as a working decision point—not an immediate blocker.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Prepare early",dueDate:"2026-09-30",stage:"Decide",stream:"Income",relationship:"Deferred decision",knowledgeStatus:"Estimate"}),

    item({id:"rental-ready",title:"Turn rental readiness into a verified packet",description:"Most documents already exist. The real work is checking target-property rules, sustainable cost, and acceptable income evidence.",area:"Build",section:"Rental Readiness",status:"In motion",priority:"Housing",timing:"Now",stage:"Prepare",stream:"Housing",relationship:"Parallel",knowledgeStatus:"Known",unlocks:["lease"]}),
    item({id:"rent-budget",parentId:"rental-ready",title:"Test the $1,100–$1,300 rent range against the workbook",description:"Include utilities, parking, pet costs, insurance, and commuting—not rent alone.",area:"Build",section:"Rental Readiness",priority:"Housing",timing:"Now",stage:"Prepare",stream:"Money",relationship:"Helpful sequence",knowledgeStatus:"Decided"}),
    item({id:"property-rules",parentId:"rental-ready",title:"Research approval rules for real candidate properties",description:"Verify income multiplier, credit expectations, documentation, deposit, and whether an explanation letter helps.",area:"Build",section:"Rental Readiness",priority:"Housing",timing:"Now",stage:"Prepare",stream:"Housing",relationship:"Parallel",knowledgeStatus:"Need information"}),
    item({id:"application-packet",parentId:"rental-ready",title:"Confirm the application packet is complete",description:"IDs, pay stubs, references, employment evidence, and dog records are mostly available.",area:"Build",section:"Rental Readiness",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Housing",relationship:"Parallel",knowledgeStatus:"Known"}),

    item({id:"apartments",title:"Explore Denver neighborhoods and apartments",description:"Look for safety, people your age, gay community, music, a nearby gym, dog access, parking, privacy, and natural light.",area:"Build",section:"Housing and Lease",priority:"Housing",timing:"Now",stage:"Prepare",stream:"Housing",relationship:"Parallel",knowledgeStatus:"Known"}),
    item({id:"apartment-shortlist",parentId:"apartments",title:"Build a light shortlist before mid-September",description:"Charm is flexible; safety, dog access, parking, privacy, gym access, and natural light are the stronger filters.",area:"Build",section:"Housing and Lease",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Housing",relationship:"Helpful sequence",knowledgeStatus:"Decided"}),
    item({id:"lease",title:"Apply, review, and sign the lease",description:"Commit only after the true monthly cost, fixed costs, pet rules, dates, fees, utilities, and move procedures are understood.",area:"Build",section:"Housing and Lease",priority:"Housing",timing:"Prepare early",dependency:"rental-ready",stage:"Commit",stream:"Housing",relationship:"Hard dependency",knowledgeStatus:"Waiting on event",unlocks:["utilities","move-plan"]}),

    item({id:"health-continuity",title:"Protect ADHD medication and insurance continuity",description:"Research how coverage, prescribing, refills, and provider transition work for the destination. Routine care is otherwise current.",area:"Build",section:"Land Softly",priority:"Safety",timing:"Now",stage:"Prepare",stream:"Health & dog",relationship:"Parallel",knowledgeStatus:"Need information"}),
    item({id:"dog-ready",title:"Keep the dog packet ready",description:"Vaccines are current through the end of the year and the records are available.",area:"Build",section:"Land Softly",status:"Completed",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Health & dog",relationship:"Parallel",knowledgeStatus:"Known"}),
    item({id:"arrival-kit",title:"Define the functional first-72-hours kit",description:"Food, cleaning supplies, self-care, eating basics, and the dog’s bowls, crate, food, and place.",area:"Build",section:"Land Softly",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Health & dog",relationship:"Parallel",knowledgeStatus:"Known"}),
    item({id:"utilities",title:"Set up address-dependent arrival administration",description:"Utilities, internet, insurance, parking, building reservations, mail, payroll, bank, pharmacy, and registration wait for a real address.",area:"Build",section:"Land Softly",priority:"Deadline",timing:"After the lease",dependency:"lease",stage:"Move",stream:"Housing",relationship:"Hard dependency",knowledgeStatus:"Waiting on event"}),
    item({id:"holiday-plan",title:"Plan the October–December family and travel season",description:"Mom’s October 1 birthday, sister’s expected November birth, Thanksgiving, Christmas, and your December 27 birthday need a shared travel-and-money view.",area:"Build",section:"Land Softly",priority:"Money",timing:"Prepare early",stage:"Prepare",stream:"Money",relationship:"Parallel",knowledgeStatus:"Known"}),

    item({id:"move-plan",title:"Choose the physical move scenario",description:"Compare shipping plus driving against a U-Haul with the car attached once volume, route, address, and quotes are known.",area:"Build",section:"Physical Move",priority:"Deadline",timing:"After the lease",dependency:"lease",stage:"Move",stream:"Clear",relationship:"Hard dependency",knowledgeStatus:"Need information"}),
    item({id:"packing",parentId:"move-plan",title:"Pack unused items, décor, and nonessential furniture first",description:"Early packing can begin without turning the whole home into a departure zone.",area:"Build",section:"Physical Move",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Parallel",knowledgeStatus:"Known"}),
    item({id:"move-day-plan",parentId:"move-plan",title:"Write the Move Day care plan",description:"Protect documents, valuables, medication, dog travel, food, sleep, and communication.",area:"Build",section:"Physical Move",priority:"Safety",timing:"After the lease",stage:"Move",stream:"Health & dog",relationship:"Helpful sequence",knowledgeStatus:"Need to think"}),
    item({id:"condition-proof",parentId:"move-plan",title:"Save departure and arrival proof",description:"Keep confirmations, receipts, address changes, utility shutoff, and unit-condition photos.",area:"Build",section:"Physical Move",priority:"Deadline",timing:"After the lease",stage:"Move",stream:"Housing",relationship:"Helpful sequence",knowledgeStatus:"Decided"}),

    item({kind:"Reference",referenceFor:["apartments","rent-budget","income-options"],id:"life-filter",title:"Use the desired life as the decision filter",description:"Choose what supports a safe, alive, creative home—without making work the whole identity.",area:"Become",section:"The Life I Want",status:"In motion",priority:"Relief",timing:"Now",stage:"Foundation",stream:"Become",relationship:"Informational",knowledgeStatus:"Known"}),
    item({kind:"Reference",referenceFor:["apartments","job-search","arrival-kit"],id:"ordinary-tuesday",parentId:"life-filter",title:"Protect the ordinary Tuesday",description:"Plants, movement, a rustic breakfast, exploration, useful work, friends, music, reading, games, movies, and rest.",area:"Become",section:"The Life I Want",priority:"Relief",timing:"Now",stage:"Foundation",stream:"Become",relationship:"Informational",knowledgeStatus:"Known"}),
    item({kind:"Reference",referenceFor:["apartments","denver-door"],id:"creative-life",parentId:"life-filter",title:"Keep music and creative growth central",description:"Creativity is a true motivation, not an upgrade to add after everything else is solved.",area:"Become",section:"The Life I Want",priority:"Relief",timing:"Now",stage:"Foundation",stream:"Become",relationship:"Informational",knowledgeStatus:"Known"}),
    item({kind:"Reference",referenceFor:["family-plan","keep-connections"],id:"relationship-boundary",title:"Carry love forward without carrying every problem",description:"Ask family for excitement about the move and growing independence—not a constant transfer of crises.",area:"Become",section:"People and Relationships",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Become",relationship:"Informational",knowledgeStatus:"Decided"}),
    item({id:"keep-connections",title:"Choose simple rhythms for Baltimore relationships",description:"Keep close friends, Mom, Sister, and Grandma visible without requiring the old relationship shape to stay unchanged.",area:"Become",section:"People and Relationships",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Become",relationship:"Parallel",knowledgeStatus:"Known"}),
    item({id:"transition-ritual",title:"Create a weekly intention and transition ritual",description:"Use music, sunlight, reflection, wonder, and weekly check-ins to hold the fears without turning them into requirements.",area:"Become",section:"Spiritual Preparation",priority:"Relief",timing:"Now",stage:"Foundation",stream:"Become",relationship:"Informational",knowledgeStatus:"Decided"}),
    item({id:"denver-door",title:"Keep a few low-pressure Denver doors visible",description:"Meg, electronic music and vocal spaces, drum and bass, a gym/PT routine, nature, and one recurring social place to discover.",area:"Become",section:"Community and Belonging",priority:"Relief",timing:"After arrival",stage:"Land",stream:"Become",relationship:"Parallel",knowledgeStatus:"Known"}),
  ],
  moveFund: {
    current: 1500, workingTarget: 2500, fullTarget: 0, status: "Known",
    source: "Randall workbook · Move Save Fund", confirmedAt: "2026-07-24",
  },
  money: [
    {id:"lease",label:"Lease & move-in",current:0,target:2500,included:"Working hope for deposit, first month, application, administration, pet, and setup costs",status:"Estimate",source:"Discovery worksheet + Randall workbook",uncertain:"Actual property concessions and lease terms"},
    {id:"move",label:"Physical move",current:0,target:0,included:"Shipping plus driving, or U-Haul with the car attached",status:"Need information",source:"Future moving quotes",uncertain:"Volume, route, and quotes"},
    {id:"loose",label:"Essential loose ends",current:0,target:0,included:"Only credit, past-due, legal, and personal items chosen as move-relevant",status:"Need to think",source:"Randall workbook · Credit Matrix + Non-Credit",uncertain:"What “complete enough” means"},
    {id:"health",label:"Health preparation",current:0,target:0,included:"Insurance, ADHD medication continuity, and provider transition",status:"Need information",source:"Discovery worksheet + provider research",uncertain:"Coverage and prescribing process"},
    {id:"home",label:"Home essentials",current:0,target:0,included:"Food, cleaning, self-care, eating basics, dog setup, then first-month furniture",status:"Need to think",source:"Randall workbook + future apartment measurements",uncertain:"What travels and what fits"},
    {id:"cushion",label:"Protected cushion",current:0,target:0,included:"Preferred two to three months of essential post-move life",status:"Estimate",source:"Randall workbook recurring expenses",uncertain:"Final housing cost and income timing"},
    {id:"travel",label:"Holiday & travel",current:0,target:0,included:"October birthday, November birth, Thanksgiving, Christmas, and December birthday",status:"Need information",source:"Randall workbook + travel decisions",uncertain:"Which trips happen and their costs"},
  ],
  routes: [
    {id:"r1",name:"Current role becomes fully remote",subtitle:"Preferred route · test in September",active:true,status:"Policy information needed",details:["Research out-of-state policy","Prepare a balanced case at the current $31.25/hour baseline","Begin conversation around the six-month mark","Use late September as a working answer date","Confirm housing-usable written evidence"]},
    {id:"r2",name:"New fully remote role",subtitle:"Parallel option · begin in September",active:false,status:"Criteria decided",details:["At least $75,000","Stable corporate work","40 hours without consuming the whole life","Use applications as a real option and leverage","Plan start and first-paycheck timing"]},
    {id:"r3",name:"Hybrid role in the destination",subtitle:"Reserve route",active:false,status:"Not active yet",details:["Use only if remote routes do not fit","Research Denver work geography","Set commute radius after neighborhood learning","Compare parking and transit","Check housing implications"]},
  ],
  vault: [
    {id:"v1",title:"Randall workbook — Credit Matrix",category:"Credit documents",url:"#",date:today,notes:"Financial source of truth for balances and collections. Do not duplicate sensitive details here."},
    {id:"v2",title:"Randall workbook — Non-Credit",category:"Tickets and bills",url:"#",date:today,notes:"Source of truth for known non-credit obligations and car estimates."},
    {id:"v3",title:"Dog records packet",category:"Dog records links",url:"#",date:today,notes:"Vaccinations and supporting records are available; vaccines are current through year-end."},
  ],
  reflections: [
    {id:"away",prompt:"What am I leaving behind?",value:"Obsession, loneliness, scarcity, self-isolation, anxiety, fear, burdens, stuckness, regret, and envy."},
    {id:"toward",prompt:"What becomes possible?",value:"A place for friends; space to heal, learn, laugh, love, see, feel, experience, and be alive."},
    {id:"tuesday",prompt:"What should an ordinary Tuesday hold?",value:"Plants, movement, a comforting breakfast, exploration, useful work, a friend, music, a nighttime routine, reading, games, a movie, and rest."},
    {id:"home",prompt:"How should home feel?",value:"My creative space and sanctuary: clean, beautiful, alive, and a place where love, happiness, and joy can gather."},
    {id:"belonging",prompt:"What feels like belonging?",value:"Creative, funny, gay, fitness-minded, nature-loving, driven people—and places where familiarity can grow."},
    {id:"money",prompt:"What is financial peace?",value:"Security in my needs, flexibility for fun and freedom, and savings for the future."},
  ],
};
