import type { Area, MoveData, MoveItem, Priority, Timing, WorkArea } from "./types";

const today = new Date().toISOString().slice(0,10);
type SeedItem = Omit<Partial<MoveItem>,"status"|"area"|"priority"|"timing"|"phase"|"type"|"workArea"|"importance"> & Pick<MoveItem,"id"|"title"> & {
  area: Area; section: string; status?: string; priority?: Priority; timing?: Timing;
};
const goalIds = new Set(["credit-plan","income-evidence","lease"]);
const projectIds = new Set(["family-plan","remote-search","chicago-hybrid","denver-hybrid","application-packet","move-plan","utilities","holiday-plan"]);
const statusFor=(status?:string):MoveItem["status"]=>status==="Completed"?"Done":status==="In motion"?"In Progress":status==="Blocked"||status==="Waiting"?"Blocked":"Not Started";
const phaseFor=(partial:SeedItem):MoveItem["phase"]=>partial.area==="Become"||partial.section==="Post Arrival"||partial.timing==="After arrival"||partial.timing==="First 72 hours"?"Post-Move":"Pre-Move";
const areaFor=(partial:SeedItem):WorkArea=>{
  if(partial.area==="Become") return partial.section==="Community and Belonging"||partial.section==="People and Relationships"?"Community":"Settling In";
  if(partial.section==="Post Arrival") return "Admin";
  if(partial.section==="Post-Move Income") return "Income";
  if(["Rental Readiness","Preferences in Search","Getting a Place"].includes(partial.section)) return "Housing";
  if(partial.section==="Physical Move — Pre") return "Packing";
  if(partial.section==="Physical Move"||partial.section==="Car, Documents and Responsibilities") return "Logistics";
  if(partial.section==="Pre-Move") return partial.id==="holiday-plan"?"Money":"Health + Marvel";
  if(partial.section==="Money, Credit and Old Obligations"||partial.section==="Allowed to Wait") return "Money";
  if(partial.section==="Family: What I Can Help With"||partial.section==="Closure Before I Leave") return "People + Closure";
  return "Admin";
};
const item=(partial:SeedItem):MoveItem=>{
  const type=goalIds.has(partial.id)?"Goal":projectIds.has(partial.id)?"Project":"Task";
  const title=partial.id==="credit-plan"?"Rental Credit Readiness":partial.id==="income-evidence"?"Housing-Ready Income":partial.id==="lease"?"Secure a Home":partial.title;
  return {
    description:"",importance:partial.optional?"Normal":["Safety","Income","Housing","Deadline","Money"].includes(partial.priority||"")?"Important":"Normal",
    phase:phaseFor(partial),type,workArea:areaFor(partial),schedule:partial.timing==="Now"?"Now":partial.timing==="Allowed to wait"||partial.timing==="After the lease"?"Later":partial.timing==="First 72 hours"?"First 72 Hours":partial.timing==="After arrival"?"First Month":"This Week",
    kind:"Action",createdAt:today,updatedAt:today,...partial,title,status:statusFor(partial.status),
    metric:partial.id==="credit-plan"?{target:625,unit:"credit score"}:partial.metric,
  };
};

export const seedData:MoveData={
  schemaVersion:9,hideCompleted:true,
  profile:{reason:"I am building a life with more privacy, creativity, nature, meaningful connection, and financial peace.",destination:"Chicago first · Denver remains a backup",targetMoveDate:"2026-10-24",backupDate:"2026-10-31",phase:"Rebuild income · strengthen credit · compare homes",currentUnlock:"Build two forms of apartment evidence in parallel: verified new income and a 625+ credit score.",protectedMonth:true},
  sectionTargets:{"Money, Credit and Old Obligations":"2026-09-30","Car, Documents and Responsibilities":"2026-10-15","Family: What I Can Help With":"2026-10-15","Closure Before I Leave":"2026-10-20","Allowed to Wait":"2026-10-24","Timeline":"2026-10-24","Move Money":"2026-10-15","Post-Move Income":"2026-09-30","Rental Readiness":"2026-10-05","Preferences in Search":"2026-09-20","Getting a Place":"2026-10-15","Pre-Move":"2026-10-20","Post Arrival":"2026-11-07","Physical Move — Pre":"2026-10-20","Physical Move":"2026-10-24","The Life I Want":"2026-11-23","People and Relationships":"2026-10-20","Spiritual Preparation":"2026-10-24","Community and Belonging":"2026-11-30","Flowering Period: First 30 Days":"2026-11-23"},
  calendarTargets:{ground:"2026-09-15",test:"2026-10-05",commit:"2026-10-24",land:"2026-11-23"},
  items:[
    item({id:"credit-plan",title:"Make and begin the plan to raise my credit score to 625+",description:"Improve the odds of qualifying for an apartment alone. Choose concrete credit actions, track the score, and adjust from real results.",area:"Clear",section:"Money, Credit and Old Obligations",priority:"Housing",timing:"Now",stage:"Foundation",stream:"Money",unlocks:["lease"]}),
    item({id:"credit-collections",kind:"Reference",referenceFor:["credit-plan"],title:"Known collections that may affect rental review",description:"Apple/Goldman, Citi, Capital One/Walmart, Xfinity, First Energy, Progressive, and GEICO are context—not a separate task or an assumption that every balance must be cleared.",area:"Clear",section:"Money, Credit and Old Obligations",status:"Completed",priority:"Housing",timing:"Now",stage:"Foundation",stream:"Money",relationship:"Informational",knowledgeStatus:"Need information"}),
    item({id:"credit-explanation",parentId:"credit-plan",optional:true,title:"Draft a credit explanation only if a target property requests one",description:"If needed, keep it factual: collections, late payments, current stability, and documented plans.",area:"Clear",section:"Money, Credit and Old Obligations",priority:"Housing",timing:"Allowed to wait",stage:"Prepare",stream:"Housing",relationship:"Waiting on event",knowledgeStatus:"Waiting on event"}),
    item({id:"md-emissions",title:"Resolve the Maryland emissions requirement",description:"Handled; it no longer needs attention.",area:"Clear",section:"Money, Credit and Old Obligations",status:"Completed",priority:"Deadline",timing:"Now",stage:"Foundation",stream:"Clear"}),
    item({id:"oil-change",title:"Get a pre-move oil change",description:"The only currently known reliability maintenance needed before the drive.",area:"Clear",section:"Car, Documents and Responsibilities",status:"Deferred",priority:"Safety",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Helpful sequence"}),
    item({id:"registration",title:"Decide which state the car will be registered in before the November expiration",description:"Use the selected destination and its timing rules. Chicago leads; Denver remains a backup.",area:"Clear",section:"Car, Documents and Responsibilities",status:"Deferred",priority:"Deadline",timing:"Prepare early",stage:"Decide",stream:"Clear",relationship:"Decision gate",knowledgeStatus:"Need information"}),
    item({id:"insurance",optional:true,title:"Compare destination car-insurance requirements when an address is known",description:"Current coverage is Progressive in Maryland. A useful final quote needs the destination and likely the address.",area:"Clear",section:"Car, Documents and Responsibilities",status:"Deferred",priority:"Money",timing:"Allowed to wait",stage:"Commit",stream:"Money",relationship:"Waiting on event",knowledgeStatus:"Waiting on event"}),
    item({id:"attic",title:"Go through the attic",description:"Decide what travels, gets donated, or gets released.",area:"Clear",section:"Car, Documents and Responsibilities",status:"Completed",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear"}),
    item({id:"family-plan",title:"Decide what help I can realistically offer Savanna, Mom, Malik, and Baby before leaving",description:"Define help with groceries, food preparation, cleaning, transportation, or finances—and where my part ends.",area:"Clear",section:"Family: What I Can Help With",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",knowledgeStatus:"Decided"}),
    item({id:"family-transport",parentId:"family-plan",optional:true,title:"Potentially help Mom identify a license or transportation next step",description:"A finite practical option, if it fits my available time and capacity.",area:"Clear",section:"Family: What I Can Help With",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",relationship:"Helpful sequence",knowledgeStatus:"Decided"}),
    item({id:"family-routine",parentId:"family-plan",title:"Simplify the grocery and basic-needs plan",description:"Create a workable way to care for ourselves without letting household needs consume all available time.",area:"Clear",section:"Family: What I Can Help With",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",knowledgeStatus:"Decided"}),
    item({id:"grandma-letter",title:"Write the letter to Grandma",description:"Acknowledge what did not land well without making her response a requirement for closure.",area:"Clear",section:"Closure Before I Leave",status:"Completed",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",knowledgeStatus:"Decided"}),
    item({id:"goodbye-time",kind:"Reflection",title:"Name the people and places I want to honor before leaving",description:"Friends, taking Mom out, Goodwill bins with my sister, the Inner Harbor, a game, The Eagle, and childhood places.",area:"Clear",section:"Closure Before I Leave",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear",knowledgeStatus:"Decided"}),
    item({id:"release-old",kind:"Reflection",title:"Name what stays in Baltimore",description:"Obsessive mindsets, scarcity, insecurity, feeling behind or lesser, and hiding desire do not have to come with me.",area:"Clear",section:"Closure Before I Leave",priority:"Relief",timing:"Prepare early",stage:"Foundation",stream:"Become",relationship:"Informational"}),
    item({id:"cosmetic-car",optional:true,title:"Toyota fender, window tint, and touch-up paint",description:"Emotionally meaningful, but the car is already safe. Revisit only if money and time allow.",area:"Clear",section:"Allowed to Wait",status:"Deferred",priority:"Someday",timing:"Allowed to wait",stage:"Land",stream:"Clear",relationship:"Deferred decision"}),
    item({id:"prebuy",kind:"Reference",referenceFor:["arrival-kit","apartments"],title:"Do not buy everything early to avoid feeling lack",description:"Functional first. Most home purchases should wait for measurements or lived experience.",area:"Clear",section:"Allowed to Wait",status:"Completed",priority:"Someday",timing:"Allowed to wait",stage:"Land",stream:"Money",relationship:"Informational",knowledgeStatus:"Decided"}),

    item({id:"income-evidence",title:"Secure income that can qualify me for housing",description:"Element income is no longer available. Secure a remote role or a hybrid role in the destination, with verification through an offer letter or paystubs.",area:"Build",section:"Post-Move Income",status:"In motion",priority:"Income",timing:"Now",stage:"Foundation",stream:"Income",unlocks:["lease"]}),
    item({id:"remote-search",parentId:"income-evidence",title:"Search and apply for a fully remote role",description:"Pursue stable work that can travel with the move and provide housing-usable income evidence.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Now",stage:"Prepare",stream:"Income"}),
    item({id:"chicago-hybrid",parentId:"income-evidence",title:"Search and apply for a hybrid role in Chicago",description:"Chicago is the leading destination, so this is the primary destination-based employment route.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Now",stage:"Prepare",stream:"Income",knowledgeStatus:"Decided"}),
    item({id:"denver-hybrid",parentId:"income-evidence",optional:true,title:"Keep a Denver hybrid search available as a backup",description:"Give Denver less attention than Chicago unless the evidence changes.",area:"Build",section:"Post-Move Income",priority:"Income",timing:"Prepare early",stage:"Prepare",stream:"Income",relationship:"Deferred decision",knowledgeStatus:"Decided"}),
    item({id:"income-proof",parentId:"income-evidence",title:"Save housing-usable income verification",description:"Keep the signed offer letter with compensation or the required new-role paystubs ready for applications.",area:"Build",section:"Rental Readiness",priority:"Housing",timing:"Prepare early",stage:"Commit",stream:"Housing",relationship:"Helpful sequence",knowledgeStatus:"Waiting on event"}),
    item({id:"property-rules",kind:"Reference",referenceFor:["application-packet","apartments","lease"],title:"Rules for a real candidate property",description:"Verify income around 2.5–3× rent, the 625+ credit target, $50–$100 application fees, deposit, pet and parking costs, plus any move-in special. Never assume a generic rule is the property’s final rule.",area:"Build",section:"Rental Readiness",priority:"Housing",timing:"Now",stage:"Prepare",stream:"Housing",relationship:"Informational",knowledgeStatus:"Need information"}),
    item({id:"application-packet",parentId:"lease",title:"Prepare the rental application",description:"Gather identification and income evidence, then compare the actual approval route for a standard lease or sublet.",area:"Build",section:"Rental Readiness",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Housing",decision:{prompt:"Which housing route fits the evidence I will have?",options:["Standard lease","Sublet"]}}),
    item({id:"apartments",kind:"Reflection",referenceFor:["lease"],title:"Explore Chicago first and Denver second",description:"Learn which neighborhoods support safety, people my age, gay community, music, a nearby gym, dog access, parking, privacy, and natural light.",area:"Build",section:"Preferences in Search",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Housing"}),
    item({id:"apartment-shortlist",kind:"Reflection",parentId:"apartments",referenceFor:["lease"],title:"Define the desired qualities of the new home",description:"Charm is flexible; safety, dog access, parking, privacy, gym access, natural light, location, space, and size guide comparison.",area:"Build",section:"Preferences in Search",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Housing",relationship:"Helpful sequence",knowledgeStatus:"Decided"}),
    item({id:"lease",title:"Apply, review, and sign the lease",description:"Commit only after verified income, a 625+ credit path, true monthly cost, pet rules, fees, utilities, and move procedures are understood. Compare leases, sublets, and specials.",area:"Build",section:"Getting a Place",priority:"Housing",timing:"Prepare early",dependency:"income-evidence",stage:"Commit",stream:"Housing",relationship:"Hard dependency",knowledgeStatus:"Waiting on event",unlocks:["utilities","move-plan"]}),
    item({id:"health-continuity",title:"Get my Vyvanse pharmacy history and a note from Dr. Dippo",description:"Save what may improve continuity with a new in-state provider; research coverage, prescribing, refills, and provider transition.",area:"Build",section:"Pre-Move",priority:"Safety",timing:"Prepare early",stage:"Prepare",stream:"Health & dog",knowledgeStatus:"Need information"}),
    item({id:"dog-ready",title:"Save Marvel’s vaccination records and upcoming dates to the Marvel folder",description:"Vaccines are current through the end of the year and the records are available.",area:"Build",section:"Pre-Move",status:"Completed",priority:"Housing",timing:"Prepare early",stage:"Prepare",stream:"Health & dog"}),
    item({id:"arrival-kit",kind:"Reflection",title:"Define the functional first-72-hours kit",description:"Food, cleaning supplies, self-care, eating basics, and Marvel’s bowls, crate, food, and place.",area:"Build",section:"Pre-Move",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Health & dog"}),
    item({id:"holiday-plan",title:"Plan for holiday and family returns",description:"Mom’s October 1 birthday, the expected November birth, Thanksgiving, Christmas, and my December 27 birthday need one travel-and-money view.",area:"Build",section:"Pre-Move",priority:"Money",timing:"Prepare early",stage:"Prepare",stream:"Money"}),
    item({id:"utilities",title:"Set up utilities, mail forwarding, a new pharmacy, and address updates",description:"Utilities, internet, insurance, parking, building reservations, mail, payroll, bank, pharmacy, and registration wait for a real address.",area:"Build",section:"Post Arrival",priority:"Deadline",timing:"After the lease",dependency:"lease",stage:"Move",stream:"Housing",relationship:"Hard dependency",knowledgeStatus:"Waiting on event"}),
    item({id:"move-plan",title:"Install a trailer hitch and reserve a small trailer",description:"Confirm volume, route, address, hitch fit, and rental cost before committing. Chicago is the leading route.",area:"Build",section:"Physical Move — Pre",priority:"Deadline",timing:"After the lease",dependency:"lease",stage:"Move",stream:"Clear",relationship:"Hard dependency",knowledgeStatus:"Need information"}),
    item({id:"packing",parentId:"move-plan",title:"Pack unused items, décor, and nonessential furniture first",description:"Begin early. Get vacuum-seal bags where they genuinely conserve space.",area:"Build",section:"Physical Move — Pre",priority:"Relief",timing:"Prepare early",stage:"Prepare",stream:"Clear"}),
    item({id:"move-day-plan",kind:"Reflection",parentId:"move-plan",title:"Write the Move Day care plan",description:"Protect documents, valuables, medication, Marvel’s travel, food, sleep, and communication.",area:"Build",section:"Physical Move — Pre",priority:"Safety",timing:"Prepare early",stage:"Move",stream:"Health & dog",relationship:"Helpful sequence",knowledgeStatus:"Need to think"}),
    item({id:"condition-proof",kind:"Reference",referenceFor:["move-plan","utilities"],title:"Keep departure and arrival proof",description:"Save confirmations, receipts, address changes, utility shutoff records, and unit-condition photos while completing the related actions.",area:"Build",section:"Physical Move",priority:"Deadline",timing:"After the lease",stage:"Move",stream:"Housing",relationship:"Informational",knowledgeStatus:"Decided"}),

    item({id:"life-filter",kind:"Reflection",referenceFor:["apartments","remote-search","chicago-hybrid"],title:"Use the desired life as the decision filter",description:"Choose what supports a safe, alive, creative home without making work the whole identity.",area:"Become",section:"The Life I Want",timing:"After arrival",stage:"Land",stream:"Become",relationship:"Informational"}),
    item({id:"ordinary-tuesday",kind:"Reflection",parentId:"life-filter",title:"Romanticize life into a new thriving routine",description:"Plants, movement, a rustic breakfast, exploration, useful work, friends, music, reading, games, movies, and rest.",area:"Become",section:"The Life I Want",timing:"After arrival",stage:"Land",stream:"Become"}),
    item({id:"creative-life",kind:"Reference",referenceFor:["apartments","life-filter"],title:"Keep music and creative growth central",description:"Creativity is a true motivation, not an upgrade to add after everything else is solved.",area:"Become",section:"The Life I Want",timing:"After arrival",stage:"Land",stream:"Become",relationship:"Informational"}),
    item({id:"relationship-boundary",kind:"Reference",referenceFor:["family-plan"],title:"Carry love forward without carrying every problem",description:"Ask family for excitement about the move and growing independence—not a constant transfer of crises.",area:"Become",section:"People and Relationships",timing:"Prepare early",stage:"Prepare",stream:"Become",relationship:"Informational",knowledgeStatus:"Decided"}),
    item({id:"keep-connections",kind:"Reflection",title:"Choose simple rhythms for Baltimore relationships",description:"Keep close friends, Mom, Sister, and Grandma visible without requiring the old relationship shape to stay unchanged.",area:"Become",section:"People and Relationships",timing:"Prepare early",stage:"Prepare",stream:"Become"}),
    item({id:"transition-ritual",kind:"Reflection",title:"Create a weekly intention and transition ritual",description:"Use music, sunlight, reflection, wonder, and weekly check-ins to hold fear without turning it into a requirement.",area:"Become",section:"Spiritual Preparation",timing:"Prepare early",stage:"Foundation",stream:"Become",knowledgeStatus:"Decided"}),
    item({id:"city-doors",kind:"Reference",referenceFor:["life-filter"],title:"Keep a few low-pressure Chicago and Denver doors visible",description:"Meg, electronic music and vocal spaces, drum and bass, a gym/PT rhythm, nature, and one recurring social place to discover.",area:"Become",section:"Community and Belonging",timing:"After arrival",stage:"Land",stream:"Become",relationship:"Informational"}),
  ],
  moveFund:{current:1500,workingTarget:2500,fullTarget:0,status:"Known",source:"Randall workbook · Move Save Fund",confirmedAt:"2026-07-24"},
  money:[
    {id:"lease",label:"Lease & move-in",current:0,target:2500,included:"Application, deposit, first month, pet and setup costs after verified specials",status:"Estimate",source:"Apartment Matrix + Randall workbook",uncertain:"Property, route, and concession"},
    {id:"move",label:"Physical move",current:0,target:0,included:"Trailer hitch, small trailer, fuel, route, and supplies",status:"Need information",source:"Future quotes",uncertain:"Address and quote"},
    {id:"loose",label:"Essential loose ends",current:0,target:0,included:"Only credit, legal, and personal items chosen as move-relevant",status:"Need to think",source:"Randall workbook",uncertain:"Credit plan"},
    {id:"health",label:"Health preparation",current:0,target:0,included:"Medication and provider continuity",status:"Need information",source:"Provider research",uncertain:"Coverage and prescribing process"},
    {id:"home",label:"Home essentials",current:0,target:0,included:"First 72 hours, dog setup, then measured essentials",status:"Need to think",source:"Apartment measurements",uncertain:"What travels and fits"},
    {id:"cushion",label:"Protected cushion",current:0,target:0,included:"Post-move essentials while new income stabilizes",status:"Estimate",source:"Randall workbook",uncertain:"Housing cost and first paycheck"},
    {id:"travel",label:"Holiday & travel",current:0,target:0,included:"October through December family events and returns",status:"Need information",source:"Randall workbook + decisions",uncertain:"Which trips happen"}],
  routes:[
    {id:"r1",name:"New fully remote role",subtitle:"Primary flexible route",active:true,status:"In active search",details:["Apply for stable fully remote work","Confirm Illinois or Colorado employment is allowed","Secure a signed offer letter or paystubs","Track start date and first paycheck","Use income evidence in housing comparisons"]},
    {id:"r2",name:"Hybrid role in Chicago",subtitle:"Primary destination route",active:false,status:"Chicago is the stronger contender",details:["Search Chicago roles and work geography","Compare commute, transit, and parking","Secure an offer letter or paystubs","Use work location to inform neighborhoods","Track total housing plus commute cost"]},
    {id:"r3",name:"Hybrid role in Denver",subtitle:"Backup destination route",active:false,status:"Lower-priority backup",details:["Keep a light Denver search","Increase effort only if evidence changes","Compare salary and commute","Secure housing-usable verification","Do not split attention equally by default"]}],
  apartments:[],
  vault:[{id:"v1",title:"Randall workbook — financial source of truth",category:"Credit documents",url:"#",date:today,notes:"Balances, spending, savings, and financial planning. Do not duplicate sensitive details here."},{id:"v2",title:"Move OS Action Items",category:"Notes",url:"https://docs.google.com/spreadsheets/d/16a_oBAJwcQxhEwdq4Ip6d0dCA-JWn0FoPEj06isqIBI/edit",date:today,notes:"Current content source for Clear, Build, and Become."},{id:"v3",title:"Marvel records folder",category:"Dog records links",url:"#",date:today,notes:"Vaccination records and upcoming dates are saved."}],
  reflections:[{id:"away",prompt:"What am I leaving behind?",value:"Obsession, loneliness, scarcity, self-isolation, anxiety, fear, burdens, stuckness, regret, and envy."},{id:"toward",prompt:"What becomes possible?",value:"A place for friends; space to heal, learn, laugh, love, see, feel, experience, and be alive."},{id:"tuesday",prompt:"What should an ordinary Tuesday hold?",value:"Plants, movement, a comforting breakfast, exploration, useful work, a friend, music, a nighttime routine, reading, games, a movie, and rest."},{id:"home",prompt:"How should home feel?",value:"My creative space and sanctuary: clean, beautiful, alive, and a place where love, happiness, and joy can gather."},{id:"belonging",prompt:"What feels like belonging?",value:"Creative, funny, gay, fitness-minded, nature-loving, driven people—and places where familiarity can grow."},{id:"money",prompt:"What is financial peace?",value:"Security in my needs, flexibility for fun and freedom, and savings for the future."}],
};
